### ISSUE TITLE
Add .env to global .gitignore file

### ISSUE THREAD

**Issue by srhoulam** [ga-wdi-boston/rails-deployment-heroku-study#1]
At some point, someone will forget to add .env to their current project's .gitignore file.

Script to set up a global gitignore file:

``` bash
if [ -e ~/.gitignore ]; then
  GIFILE=~/.gitignore_global
else
  GIFILE=~/.gitignore
fi

touch $GIFILE
git config --global core.excludesfile $GIFILE

echo '.env' >> $GIFILE
```

Reference: https://help.github.com/articles/ignoring-files/

**Comment by jrhorn424** [comment]
I believe this should be tracked elsewhere.
