### ISSUE TITLE
Rename to rails-heroku-setup-guide.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/rails-deployment-heroku-study#18]
À la `aws-s3-setup-guide`

@ga-wdi-boston/core Without objection.

**Comment by RealWeeks** [comment]
@gaand updated. okay to close?

**Comment by jrhorn424** [comment]
The name of the repo doesn't match the title of the issue. Is it correct?

**Comment by jrhorn424** [comment]
What should it be?

**Comment by gaand** [comment]
I think the name of the repo should be the name in the issue.

**Comment by BenGitsCode** [comment]
I'm going to follow @gaand 's lead here and rename this repo to `rails-heroku-setup-guide` per this issue.

Changing it in planning issue, this repo and the calendar as well.

**Comment by BenGitsCode** [comment]
Actually, I seem to no longer haver repo settings permissions. @ga-wdi-boston/core the ball is in your court.
