### ISSUE TITLE
Use dotenv for secrets.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/rails-deployment-heroku-study#19]
See commit closing ga-wdi-boston/rails-api-template#8 and comment on ga-wdi-boston/rails-api-template#13.

**Comment by RealWeeks** [comment]
@gaand instructions updated in commit 6252370 okay to close?

**Comment by jrhorn424** [comment]
I do not see anything about dotenv in that commit. Can you point to a line number?

**Comment by gaand** [comment]
@J-Weeks Agreed. Is there a different commit for that?
