### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/rails-deployment-heroku-study#28]
Instructions say:

**You'll probably see something like this:**
![screen shot 2017-03-11 at 4 07 20 pm](https://cloud.githubusercontent.com/assets/24608045/23826887/dba73f20-0674-11e7-8cc1-97cfc423d2ab.png)

Should the instructions say "it **must** show something like this" ?

Because after following all the steps I plainly get the below line at the top left of the browser:
```
{"index":{"title":"Express Template","environment":"production"}}
```

I am not getting any errors but it is not what it "**probably**" should show....

**Comment by bernardlee** [comment]
That's because this guide is for Ruby on Rails, not Express.js.

**Comment by doremaxime** [comment]
Yeah i saw that but since it is in the prerequisites i thought maybe in the end it would be the same message that pops up that we should see since it's for heroku too.

**Comment by doremaxime** [comment]
not a rails app.
