### ISSUE TITLE
Add in a `rails r` script for populating the database to run on Heroku, so students don't do it with `rake db:seed`

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/rails-deployment-heroku-study#4]
Here's one I used in the demo.

``` ruby
[
  {title: "Labyrinth", release_year: 1986},
  {title: "Silence of the Lambs", release_year: 1991},
  {title: "The Big Lebowski", release_year: 1998},
  {title: "The Dark Knight Rises", release_year: 2012}
].each do |movie_hash|
  Movie.create(movie_hash)
end
```

**Comment by gaand** [comment]
We should discuss if a rake task makes more sense (I think it does).

**Comment by jrhorn424** [comment]
https://github.com/ga-wdi-boston/rails-api-template now includes a `rake db:examples` task to fill the database with examples from `db/examples.rb`. @gaand has suggested a few improvements.

I suggest we track any improvements over there and close this issue.

**Comment by GA-MEB** [comment]
Agreed.
