### ISSUE TITLE
Essential parts of this presentation

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/rails-deployment-heroku-study#7]
I suggest following checklist-driven-development :tm:

In addition to learning objectives, students should be able to follow these steps when deploying new apps:
-   [ ] Create a heroku app from the command line
-   [ ] Push the latest code to heroku
-   [ ] Migrate the production database

Other essential parts: twelve factor gem, specify a ruby version in Gemfile.

**Comment by jrhorn424** [comment]
Also, I really like the commands reference table and the warning about the "file" system.

**Comment by RealWeeks** [comment]
added to objectives and kept commands refs and warning.
